# Generated by Django 5.0.2 on 2024-06-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_detail',
            old_name='c_address',
            new_name='correspondance_address',
        ),
        migrations.RenameField(
            model_name='personal_detail',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='personal_detail',
            old_name='p_address',
            new_name='permanent_address',
        ),
        migrations.AddField(
            model_name='bank_detail',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personal_detail',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school_detail',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject_mark',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
