# Generated by Django 5.0.2 on 2024-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_rename_c_address_personal_detail_correspondance_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_detail',
            name='identity',
            field=models.CharField(choices=[('pan card', 'Pan Card'), ('ration card', 'Ration Card'), ('passport', 'Passport'), ('adhar card', 'Adhar Card'), ('other', 'Other Id')], max_length=12),
        ),
        migrations.AlterField(
            model_name='school_detail',
            name='medium',
            field=models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English'), ('other', 'Other')], max_length=8),
        ),
        migrations.AlterField(
            model_name='school_detail',
            name='result_status',
            field=models.CharField(choices=[('pass', 'Passed'), ('appearing', 'Appearing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school_detail',
            name='rollnumber',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='school_detail',
            name='school_type',
            field=models.CharField(choices=[('private', 'Private'), ('government', 'Government'), ('semi-government', 'Semi-government')], max_length=16),
        ),
    ]
