# Generated by Django 5.0.2 on 2024-06-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_personal_detail_identity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_mark',
            old_name='maximum1',
            new_name='maximum_marks_Sub1',
        ),
        migrations.RenameField(
            model_name='subject_mark',
            old_name='maximum2',
            new_name='maximum_marks_Sub2',
        ),
        migrations.RenameField(
            model_name='subject_mark',
            old_name='maximum3',
            new_name='maximum_marks_Sub3',
        ),
        migrations.RenameField(
            model_name='subject_mark',
            old_name='maximum4',
            new_name='maximum_marks_Sub4',
        ),
        migrations.RenameField(
            model_name='subject_mark',
            old_name='maximum5',
            new_name='maximum_marks_Sub5',
        ),
        migrations.RenameField(
            model_name='subject_mark',
            old_name='obtained1',
            new_name='obtained_marks_Sub1',
        ),
        migrations.RenameField(
            model_name='subject_mark',
            old_name='obtained2',
            new_name='obtained_marks_Sub2',
        ),
        migrations.RenameField(
            model_name='subject_mark',
            old_name='obtained3',
            new_name='obtained_marks_Sub3',
        ),
        migrations.RenameField(
            model_name='subject_mark',
            old_name='obtained4',
            new_name='obtained_marks_Sub4',
        ),
        migrations.RenameField(
            model_name='subject_mark',
            old_name='obtained5',
            new_name='obtained_marks_Sub5',
        ),
        migrations.RemoveField(
            model_name='subject_mark',
            name='subject_percent1',
        ),
        migrations.RemoveField(
            model_name='subject_mark',
            name='subject_percent2',
        ),
        migrations.RemoveField(
            model_name='subject_mark',
            name='subject_percent3',
        ),
        migrations.RemoveField(
            model_name='subject_mark',
            name='subject_percent4',
        ),
        migrations.RemoveField(
            model_name='subject_mark',
            name='subject_percent5',
        ),
    ]
