# Generated by Django 5.0.2 on 2024-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_rename_maximum1_subject_mark_maximum_marks_sub1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_detail',
            name='reservation',
            field=models.CharField(choices=[('unreserved', 'Unreserved'), ('ews', 'EWS'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='special_reservation',
            field=models.CharField(choices=[('none', 'None'), ('k-migrant', 'Kashmir Migrant'), ('staff quota', 'Staff Quota'), ('sports', 'Sports Quota'), ('pwd', 'PWD')], max_length=12),
        ),
    ]
