# Generated by Django 5.0.2 on 2024-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_personal_detail_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('candidate_image', models.ImageField(upload_to='')),
                ('signature_image', models.ImageField(upload_to='')),
                ('reservation_certificate', models.FileField(null=True, upload_to='')),
                ('special_reservation_certificate', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='mobile',
            field=models.CharField(max_length=14),
        ),
    ]
