# Generated by Django 5.0.2 on 2024-06-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_certificates_alter_personal_detail_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('family_detail', models.BooleanField(default=False)),
                ('personal_detail', models.BooleanField(default=False)),
                ('school_detail', models.BooleanField(default=False)),
                ('subject_mark', models.BooleanField(default=False)),
                ('bank_detail', models.BooleanField(default=False)),
                ('certificates', models.BooleanField(default=False)),
            ],
        ),
    ]
