# Generated by Django 5.0.2 on 2024-06-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='school_detail',
            new_name='education',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='subject_mark',
        ),
    ]
