# Generated by Django 5.0.2 on 2024-06-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_rename_school_detail_progress_education_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='progress',
            new_name='progressreport',
        ),
    ]
