# Generated by Django 5.0.2 on 2024-06-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_rename_progress_progressreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='certificates',
        ),
    ]
