# Generated by Django 5.0.2 on 2024-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_remove_progressreport_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='certificates',
            field=models.BooleanField(default=False),
        ),
    ]
