# Generated by Django 5.0.2 on 2024-06-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_progressreport_certificates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='special_reservation_certificate',
            new_name='identity_proof',
        ),
    ]
