# Generated by Django 5.0.2 on 2024-06-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0014_rename_special_reservation_certificate_certificates_identity_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='candidate_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='identity_proof',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='mark_sheet',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='reservation_certificate',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='signature_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
