# Generated by Django 5.0.2 on 2024-06-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_alter_certificates_candidate_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='candidate_image',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='identity_proof',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='mark_sheet',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='reservation_certificate',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='signature_image',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='username',
        ),
    ]
