# Generated by Django 5.0.2 on 2024-06-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0016_remove_certificates_candidate_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_mark',
            old_name='subject3',
            new_name='subject33',
        ),
    ]
