# Generated by Django 5.0.2 on 2024-06-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0017_rename_subject3_subject_mark_subject33'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_mark',
            old_name='subject33',
            new_name='subject3',
        ),
    ]
