# Generated by Django 5.0.2 on 2024-06-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0019_remove_progressreport_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='certificates',
        ),
    ]
