# Generated by Django 5.0.2 on 2024-06-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0020_delete_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_detail',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
