# Generated by Django 5.0.2 on 2024-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0022_alter_subject_mark_subject1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_mark',
            name='subject2',
            field=models.CharField(max_length=10),
        ),
    ]
