# Generated by Django 5.0.2 on 2024-06-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0024_alter_subject_mark_subject2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_mark',
            name='subject1',
            field=models.CharField(choices=[('maths', 'Mathematics'), ('english', 'English'), ('hindi', 'Hindi'), ('sanskrit', 'Sanskrit'), ('comp', 'Computer Science'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('bio', 'Biology'), ('accounts', 'Accounts'), ('economics', 'Economics'), ('business', 'Business Studies'), ('physical', 'Physical Sciences'), ('history', 'History'), ('geography', 'Geography'), ('psychology', 'Psychology'), ('political', 'Political Science')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject_mark',
            name='subject2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject_mark',
            name='subject3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject_mark',
            name='subject4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject_mark',
            name='subject5',
            field=models.CharField(max_length=10),
        ),
    ]
